### ISSUE TITLE
container.sh requires a username/password

### ISSUE THREAD

**Issue by alphafox02** [asset-group/5ghoul-5g-nr-attacks#1]
I'm sure you're already aware, but sharing anyways. 

```
mkdir 5ghoul # Create 5ghoul folder
curl -LJO https://github.com/asset-group/5ghoul-5g-nr-attacks/raw/master/container.sh
chmod +x container.sh # Give exec. permission to the 5Ghoul container script
./container.sh release-5g # This will pull and start the terminal of the 5Ghoul container
sudo bin/5g_fuzzer --MCC=001 --MNC=01 # This will start the rogue base station inside the container
```
Assuming there needs to be a "pull" in between container.sh and release-5g. Also, looking over the container.sh it assumes we have a username/password?

**Comment by alphafox02** [comment]
Just needed to be logged into Docker

**Comment by Matheus-Garbelini** [comment]
@alphafox02 you can comment that login line on container.sh, it's not required. I've pushed a commit that removes this.

**Comment by alphafox02** [comment]
Thank you. Excited to dig in more. I have an x310/b205mini, but I realized I have to change up my UE for a 5G one. I think I have an older iPhone 8 that has 5G.
