### ISSUE TITLE
which version of open5gs the author is using

### ISSUE THREAD

**Issue by lpj12121** [asset-group/5ghoul-5g-nr-attacks#13]
Hello, may I ask which version of open5gs the author is using? I have installed the latest version 2.7.0 and the latest OAI RAN, but the mobile phone has no signal.

Looking forward to your reply, best wishes.

**Comment by shuimoshusheng** [comment]
> Hello, may I ask which version of open5gs the author is using? I have installed the latest version 2.7.0 and the latest OAI RAN, but the mobile phone has no signal.
> 
> Looking forward to your reply, best wishes.

@lpj12121  See README https://github.com/asset-group/5ghoul-5g-nr-attacks#2--quick-start-docker-container or https://github.com/asset-group/5ghoul-5g-nr-attacks#6-%EF%B8%8F-optional-build-5ghoul-software-from-source 

If you need detailed information, you can view it [](https://github.com/asset-group/5ghoul-5g-nr-attacks/blob/master/build.sh) perhaps [](https://github.com/asset-group/5ghoul-5g-nr-attacks/blob/master/container.sh). 

Also, you can close #12  and iusse #13 now.
