### ISSUE TITLE
adb: device 'UWEUW4XG8XCA8PWS' not found

### ISSUE THREAD

**Issue by qiqingh** [asset-group/5ghoul-5g-nr-attacks#14]
Hello, I built it from an Ubuntu 18.04 host environment and connected a USRP B210, when running the bin/5g_fuzzer I noticed there always return the multiple duplicated follwing message:

"adb: device 'UWEUW4XG8XCA8PWS' not found"

Could you please give me any insights on this information? will this be an issue when doing the test? Thanks!

**Comment by alphafox02** [comment]
That's set in I believe one of the two json config files found in the configs folder. Before launching the container, look in the 5ghoul configs directory.

**Comment by qiqingh** [comment]
Hi @alphafox02 , yes I also find these two JSON configs, shall we make any changes to the config that include this adb information?

**Comment by alphafox02** [comment]
I think it has no impact on running 5Ghoul, just add the global timeout option to the command line as if mentions towards the top of the readme. I can’t recall but under one of the config files I think you can chance a flag to false so the adb check doesn’t occur. I hope that’s helpful. I’m hoping to get my hands on a b210 soon in place of my x310.

**Comment by Matheus-Garbelini** [comment]
> Hello, I built it from an Ubuntu 18.04 host environment and connected a USRP B210, when running the bin/5g_fuzzer I noticed there always return the multiple duplicated follwing message:
> 
> "adb: device 'UWEUW4XG8XCA8PWS' not found"
> 
> Could you please give me any insights on this information? will this be an issue when doing the test? Thanks!

Hi @qiqingh by default 5ghoul looks for a android phone to monitor. You can disable this warning by disabling the monitor  (change from true to false) in the following line of the config. file: 
https://github.com/asset-group/5ghoul-5g-nr-attacks/blob/master/configs/5gnr_gnb_config.json#L205

**Comment by qiqingh** [comment]
@Matheus-Garbelini Got it, thanks for your confirmation!

**Comment by qiqingh** [comment]
> I think it has no impact on running 5Ghoul, just add the global timeout option to the command line as if mentions towards the top of the readme. I can’t recall but under one of the config files I think you can chance a flag to false so the adb check doesn’t occur. I hope that’s helpful. I’m hoping to get my hands on a b210 soon in place of my x310.

Thank you for your additional information!
