### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by qiqingh** [asset-group/5ghoul-5g-nr-attacks#16]
Hello, I'm currently working on Ubuntu 18.04, with cmake version 3.24.1 and clang 15. However, I encounter an error when executing either './build.sh all' or './build.sh'. The error reads:

'ninja: Entering directory `build'
ninja: error: '/home/Desktop/5ghoul-5g-nr-attacks/libs/wireshark/ui/qt/-silent', needed by 'libs/wireshark/ui/qt/-silent.qm', missing and no known rule to make it'

Interestingly, executing './build.sh dev' results in a successful build, but when I run bin/5g_fuzzer, it appears that 'hostapd/idemptables' is missing from './3rd-party/'. Can you confirm if the absence of './3rd-party/hostapd/idemptables' will been an issue?

**Comment by Matheus-Garbelini** [comment]
Hi @qiqingh have you tried the command `./build.sh all`? ./build.sh without any arguments only works after at least one build is done with arguments `all` or `dev`.

This idemtables is not an issue but I will need to add it in a later commit to avoid errors during execution. The container should contain this file however.

**Comment by qiqingh** [comment]
Hi @Matheus-Garbelini Thank you for your confirmation on idemtables.

Please find my build log in the attachment, thank you!
[log.txt](https://github.com/asset-group/5ghoul-5g-nr-attacks/files/13833927/log.txt)

**Comment by Matheus-Garbelini** [comment]
Hi @qiqingh have you run command `./requirements.sh dev`?
I think this was missing from the readme.

**Comment by qiqingh** [comment]
@Matheus-Garbelini Thanks for your update! the problem get resolved. Thanks for your help!
