### ISSUE TITLE
Docker Build error

### ISSUE THREAD

**Issue by Dustin12138** [asset-group/5ghoul-5g-nr-attacks#17]
Hi,

When I built the docker images I noticed the error in the image. The output was generated when I ran the script container.sh.
<img width="619" alt="Screenshot 2024-01-05 211421" src="https://github.com/asset-group/5ghoul-5g-nr-attacks/assets/50658447/e02d7bfe-1d4d-4b61-82ed-6b59c02c4a68">

I created the corresponding directory but when I reran the shell script, I received the same error indicating the container was not running. Also, it seems that no docker container is running:
<img width="355" alt="Screenshot 2024-01-05 211714" src="https://github.com/asset-group/5ghoul-5g-nr-attacks/assets/50658447/d8ec0839-edfe-4160-a8d1-65c08852bf08">

I'm using Ubuntu 18.04 and the Docker version is the same as suggested. What should I do to solve this problem?

Thanks,

Dustin12138

**Comment by alphafox02** [comment]
I’m using 22.04 (DragonOS), are you trying to compile the source or just run the docker? In my case with 22.04 I do not have the issue you’re seeing. Under requirements it mentions that 18.04 had only been tested for bare-metal non docker.

**Comment by Dustin12138** [comment]
> I’m using 22.04 (DragonOS), are you trying to compile the source or just run the docker? In my case with 22.04 I do not have the issue you’re seeing. Under requirements it mentions that 18.04 had only been tested for bare-metal non docker.

I'm trying to run the docker. It seems that the quick start does not require a specific version of OS.

**Comment by Matheus-Garbelini** [comment]
> Hi,
> 
> When I built the docker images I noticed the error in the image. The output was generated when I ran the script container.sh. <img alt="Screenshot 2024-01-05 211421" width="619" src="https://private-user-images.githubusercontent.com/50658447/294645033-e02d7bfe-1d4d-4b61-82ed-6b59c02c4a68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjA1MDEsIm5iZiI6MTcwNDUyMDIwMSwicGF0aCI6Ii81MDY1ODQ0Ny8yOTQ2NDUwMzMtZTAyZDdiZmUtMWQ0ZC00YjYxLTgyZWQtNmI1OWMwMmM0YTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA1NTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNzA2MWZmZDVkYTcxZWE1ZjM1ZjZjMzFmMTUxZWZiNjdmOWM1M2JkNGRlMGZhMDU5NjVlNjA4Y2E5Mzc3ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-KzdnpiCsnOq86dqHVj3fyNHiS_82WHx7afA1IxYnP4">
> 
> I created the corresponding directory but when I reran the shell script, I received the same error indicating the container was not running. Also, it seems that no docker container is running: <img alt="Screenshot 2024-01-05 211714" width="355" src="https://private-user-images.githubusercontent.com/50658447/294645116-d8ec0839-edfe-4160-a8d1-65c08852bf08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjA1MDEsIm5iZiI6MTcwNDUyMDIwMSwicGF0aCI6Ii81MDY1ODQ0Ny8yOTQ2NDUxMTYtZDhlYzA4MzktZWRmZS00MTYwLWE4ZDEtNjVjMDg4NTJiZjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA1NTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ODc1MmJjZmMxOGE0ZTc3NmI4MDFiM2I5ZjZlNzE1MDI5YzAxZjI1Mzg0NjIyYzk4ODI4MzQ3MjI1NDViMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7sh1kA6Yc8P_sAtRO9uDRxyCn1McoP5ru1ivDdv-Dx8">
> 
> I'm using Ubuntu 18.04 and the Docker version is the same as suggested. What should I do to solve this problem?
> 
> Thanks,
> 
> Dustin12138

Hi, can you remove the `&> /dev/null` from this line (https://github.com/asset-group/5ghoul-5g-nr-attacks/blob/master/container.sh#L135) and post the output of your terminal here? After creating the .Xauthority file (sudo touch /root/.Xauthority), you might be getting an error from docker when starting the container.

**Comment by Dustin12138** [comment]
Hi,

Here is the output after modifying the script.
<img width="1113" alt="image" src="https://github.com/asset-group/5ghoul-5g-nr-attacks/assets/50658447/96b82483-80a6-4429-84d1-bb8e61b761eb">

**Comment by Matheus-Garbelini** [comment]
Hi @Dustin12138 you can try removing your .Xauth folder. The issue is that docker is expecting a file there, not a folder:
`sudo rm -df /root/.Xauthority`. Then you just need to create an empty file with `sudo touch /root/.Xauthority`.

**Comment by Dustin12138** [comment]
Thanks Matheus, the problem is solved. Closing this issue.
