### ISSUE TITLE
(Question) start_container funtions

### ISSUE THREAD

**Issue by alphafox02** [asset-group/5ghoul-5g-nr-attacks#2]
I notice on 22.04 when running ./container.sh run release-5g that it'll almost immediately kill my remote vnc desktop connection. I'll have to jump over to a local monitor to pick up where I was working. 

When I go looking at the container.sh script I can see the start_container_dev/release functions and it got me trying to understand what's going on there with the X11. I should note that the command does spit out a failure to connect to the bus when ran through a vnc connection. 

What is the intent of that portion of the script? Does it need to be altering x11 settings?

**Comment by Matheus-Garbelini** [comment]
> What is the intent of that portion of the script? Does it need to be altering x11 settings?

@alphafox02 X11 server of the host is shared with the container so you can open the GUI or the customized Wireshark (`bin/wireshark` inside the container). The included Wireshark is so we can observe the live captures (saved to `logs` folder). 
This could, however, present some problem to VNC. Usually our team uses [AnyDesk](https://anydesk.com/en) (using local network ip), which does not show any problem. Will try with VNC sometime to see check for a fix.

In the meantime, I would recommend you to just comment the following lines to prevent X11 from the host to be used:
 https://github.com/asset-group/5ghoul-5g-nr-attacks/blob/master/container.sh#L97-L99

> I should note that the command does spit out a failure to connect to the bus when ran through a vnc connection.
If you mean that failed to connect to dbus, such is normal and common when re-entering to the container bash terminal.
