### ISSUE TITLE
Phone Configuration Confusion

### ISSUE THREAD

**Issue by qiqingh** [asset-group/5ghoul-5g-nr-attacks#21]
Hello, I noticed in Chapter 3, titled 'Launching a 5Ghoul Attack,' a reference stating, 'More details are provided in the Section on Phone Configuration.' Could you please direct me to the specific chapter or section where I can find information about Phone Configuration?

**Comment by Matheus-Garbelini** [comment]
@qiqingh This section has not been added yet. It is supposed to have more details on how to configure the phone for the fuzzing process. However, for just connection test with 5Ghoul, no special config is needed for smartphones other than a working SIM card that preferably has MCC=001 and MNC=01.

**Comment by qiqingh** [comment]
Got it, thanks for your informaiton.
