### ISSUE TITLE
sysmoISIM-SJA2 programmable SIM/USIM/ISIM cards (Question)

### ISSUE THREAD

**Issue by alphafox02** [asset-group/5ghoul-5g-nr-attacks#8]
A pack of sysmoISIM-SJA2 programmable SIM/USIM/ISIM cards arrived today. I finally got around to inserting one into the Edge 20 and to my surprise, under prefer preferred network type, 5g is not an option. However, if I insert a Tmobile sim the option is available.

I noticed the SJA2 was mentioned in the README, just curious now if that exact one has enabled you all to access 5G?

**Comment by alphafox02** [comment]
As a follow up, I checked under the *#*#4636#*#* menu 5G/LTE debugging information and it seems to show all NSA bands enabled (assuming those are 5G). Under phone info there's a preferred network type, which having looked just now, for some reason set itself to GSM/WCDMA/LTE (PRL) after I just had it set to NR/LTE/GSM/WCDMA.

**Comment by lpj12121** [comment]
Now, I have usrp and installed a brand new ubuntu environment. I want to know what software needs to be pre-installed in advance. Can you tell me？

**Comment by alphafox02** [comment]
Follow the steps listed in the main Readme (main project page) and that’ll install docker and all that you need, it’s pretty well laid out. When you say usrp, is it a b210? If not, that’ll likely be a problem. 

I’ve also swapped out my Edge 20 for a gl inet modem that’s coming. I’m sure the SIM cards are fine and it may have just been the phone that was giving me issues.
